started at 5:52

# Задание 1

Создайте numpy array с элементами от числа N до 0 (например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])).

In [54]:
import numpy as np

In [56]:
N=10
x = np.arange( N-1, -1, -1 )
print(x)
#print(type(x))

[9 8 7 6 5 4 3 2 1 0]


continued at 6:23
paused at 6:55
continued at 7:10

# Задание 2

Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.

In [58]:
matr=np.diag(x, k=0)

In [60]:
type(matr)

numpy.ndarray

In [64]:
#sum(matr)
sum(sum(matr))
#sum(sum(np.diag(x, k=0)))

45

continued at 7:20
paused at 7:25
continued at 9:01

# Задание 3

Скачайте с сайта https://grouplens.org/datasets/movielens/ датасет любого размера. 
Определите какому фильму было выставлено больше всего оценок 5.0.

In [2]:
import pandas as pd
ratings = pd.read_csv('/home/arseny/Downloads/data-scientist4-master (4)/data-scientist4-master/2. Python for analytics/2.5 Python - Numpy, scipy/ml-20m/ratings.csv')


In [ ]:
#ratings[ ratings.rating == 5.0 ].groupby('movieId').count().sort_values('movieId', ascending=False).head
#ratings.head()
#ratings.groupby('userid').count().sort_values('movieId', ascending=False).head()

#ratings[ ratings.rating == 5.0 ].groupby('userId').count()


top_rated=ratings[ ratings.rating == 5.0 ].groupby(['movieId'])['userId'].count().reset_index(name='count').sort_values(['count'], ascending=False).head(10)


#['movieid'].count().sort_values(ascending=False).


In [ ]:
movies=pd.read_csv('/home/arseny/Downloads/data-scientist4-master (4)/data-scientist4-master/2. Python for analytics/2.5 Python - Numpy, scipy/ml-20m/movies.csv')

#joined = top_rated.merge(movies, on='movieId', how='left')
joined = pd.merge(top_rated, movies, on='movieId', how='left')
joined.head(1)

continued at 10:47
paused at 10:52
continued at 00:06

# Задание 4

По данным файла power.csv посчитайте суммарное потребление стран Прибалтики 
(Латвия, Литва и Эстония) категорий 4, 12 и 21 за период с 2005 по 2010 года. 
Не учитывайте в расчетах отрицательные значения quantity.

In [66]:
import pandas as pd
#power=pd.read_csv('/home/arseny/Downloads/data-scientist4-master (4)/data-scientist4-master/2. Python for analytics/2.5 Python - Numpy, scipy/ml-20m/movies.csv')
data = pd.read_csv('power.csv')

In [98]:
#data.head()
#data['country'].unique()
#data['category'].unique()
data[(
    (data['country']=='Estonia') 
    | (data['country']=='Lithuania') 
    | (data['country']=='Latvia')) 
     & 
    (
        (data['year']>2004) 
        & (data['year']<2011)
    )
& ((data['category']==4) 
    | (data['category']==12) 
    | (data['category']==21))]['quantity'].sum()
#data['country' in ('Latvia', 'Lithuania', 'Estonia')].head()

240481.0

# Задание 5

Решите систему уравнений:
4x + 2y + z = 4
x + 3y = 12
5y + 4z = -3

In [106]:
a = np.array( [ [4, 2, 1], [1, 3, 0], [0, 5, 4]] )
b = np.array(  [4, 12, -3]  )

In [107]:
print(a, b)

[[4 2 1]
 [1 3 0]
 [0 5 4]] [ 4 12 -3]


In [108]:
from numpy import linalg
linalg.solve(a, b)

array([ 0.46666667,  3.84444444, -5.55555556])

finished at 01:07. Total - 4:12