In [3]:
# import the necessary packages
from scipy.spatial import distance as dist
from collections import OrderedDict
import numpy as np

class CentroidTracker():
    def __init__(self, maxDisappeared=50):
        # initialize the next unique object ID along with two ordered
        # dictionaries used to keep track of mapping a given object
        # ID to its centroid and number of consecutive frames it has
        # been marked as "disappeared", respectively
        self.nextObjectID = 0
        self.objects = OrderedDict()
        self.disappeared = OrderedDict()

        # store the number of maximum consecutive frames a given
        # object is allowed to be marked as "disappeared" until we
        # need to deregister the object from tracking
        self.maxDisappeared = maxDisappeared
    
    def register(self, centroid):
        # when registering an object we use the next available object
        # ID to store the centroid
        self.objects[self.nextObjectID] = centroid
        self.disappeared[self.nextObjectID] = 0
        self.nextObjectID += 1
        
    def deregister(self, objectID):
        # to deregister an object ID we delete the object ID from
        # both of our respective dictionaries
        del self.objects[objectID]
        del self.disappeared[objectID]
        
    def update(self, rects):
        # check to see if the list of input bounding box rectangles
        # is empty
        if len(rects) == 0:
            # loop over any existing tracked objects and mark them
            # as disappeared
            for objectID in self.disappeared.keys():
                self.disappeared[objectID] += 1
 
                # if we have reached a maximum number of consecutive
                # frames where a given object has been marked as
                # missing, deregister it
                if self.disappeared[objectID] > self.maxDisappeared:
                    self.deregister(objectID)
 
            # return early as there are no centroids or tracking info
            # to update
            return self.objects
        
        # initialize an array of input centroids for the current frame
        inputCentroids = np.zeros((len(rects), 2), dtype="int")
 
        # loop over the bounding box rectangles
        for (i, (startX, startY, endX, endY)) in enumerate(rects):
            # use the bounding box coordinates to derive the centroid
            cX = int((startX + endX) / 2.0)
            cY = int((startY + endY) / 2.0)
            inputCentroids[i] = (cX, cY)
            
        # if we are currently not tracking any objects take the input
        # centroids and register each of them
        if len(self.objects) == 0:
            for i in range(0, len(inputCentroids)):
                self.register(inputCentroids[i])
                
        # otherwise, are are currently tracking objects so we need to
        # try to match the input centroids to existing object
        # centroids
        else:
            # grab the set of object IDs and corresponding centroids
            objectIDs = list(self.objects.keys())
            objectCentroids = list(self.objects.values())
 
            # compute the distance between each pair of object
            # centroids and input centroids, respectively -- our
            # goal will be to match an input centroid to an existing
            # object centroid
            D = dist.cdist(np.array(objectCentroids), inputCentroids)
 
            # in order to perform this matching we must (1) find the
            # smallest value in each row and then (2) sort the row
            # indexes based on their minimum values so that the row
            # with the smallest value is at the *front* of the index
            # list
            rows = D.min(axis=1).argsort()
 
            # next, we perform a similar process on the columns by
            # finding the smallest value in each column and then
            # sorting using the previously computed row index list
            cols = D.argmin(axis=1)[rows]
            
            # in order to determine if we need to update, register,
            # or deregister an object we need to keep track of which
            # of the rows and column indexes we have already examined
            usedRows = set()
            usedCols = set()
 
            # loop over the combination of the (row, column) index
            # tuples
            for (row, col) in zip(rows, cols):
                # if we have already examined either the row or
                # column value before, ignore it
                # val
                if row in usedRows or col in usedCols:
                    continue
 
                # otherwise, grab the object ID for the current row,
                # set its new centroid, and reset the disappeared
                # counter
                objectID = objectIDs[row]
                self.objects[objectID] = inputCentroids[col]
                self.disappeared[objectID] = 0
 
                # indicate that we have examined each of the row and
                # column indexes, respectively
                usedRows.add(row)
                usedCols.add(col)
                
            # compute both the row and column index we have NOT yet
            # examined
            unusedRows = set(range(0, D.shape[0])).difference(usedRows)
            unusedCols = set(range(0, D.shape[1])).difference(usedCols)
            
            # in the event that the number of object centroids is
            # equal or greater than the number of input centroids
            # we need to check and see if some of these objects have
            # potentially disappeared
            if D.shape[0] >= D.shape[1]:
                # loop over the unused row indexes
                for row in unusedRows:
                    # grab the object ID for the corresponding row
                    # index and increment the disappeared counter
                    objectID = objectIDs[row]
                    self.disappeared[objectID] += 1
 
                    # check to see if the number of consecutive
                    # frames the object has been marked "disappeared"
                    # for warrants deregistering the object
                    if self.disappeared[objectID] > self.maxDisappeared:
                        self.deregister(objectID)
                        
            # otherwise, if the number of input centroids is greater
            # than the number of existing object centroids we need to
            # register each new input centroid as a trackable object
            else:
                for col in unusedCols:
                    self.register(inputCentroids[col])
 
        # return the set of trackable objects
        return self.objects

In [4]:
np.random.seed(42)
objectCentroids = np.random.uniform(size=(2, 2))
centroids = np.random.uniform(size=(3, 2))
D = dist.cdist(objectCentroids, centroids)
print(D)
print(D.min(axis=1))
#array([0.32755369, 0.17058938])
rows = D.min(axis=1).argsort()
print(rows)
D.argmin(axis=1)
#array([1, 2])
cols = D.argmin(axis=1)[rows]
print(cols)
#array([2, 1])

print(list(zip(rows, cols)))
#[(1, 2), (0, 1)]

[[0.82421549 0.32755369 0.33198071]
 [0.72642889 0.72506609 0.17058938]]
[0.32755369 0.17058938]
[1 0]
[2 1]
[(1, 2), (0, 1)]


## Original version (caffe)

In [3]:
# import the necessary packages
#rom pyimagesearch.centroidtracker import CentroidTracker
from imutils.video import VideoStream
import numpy as np
import argparse
import imutils
import time
import cv2
 
# construct the argument parse and parse the arguments
ap = argparse.ArgumentParser()
ap.add_argument("-p", "--prototxt", required=True,
    help="path to Caffe 'deploy' prototxt file")
ap.add_argument("-m", "--model", required=True,
    help="path to Caffe pre-trained model")
ap.add_argument("-c", "--confidence", type=float, default=0.5,
    help="minimum probability to filter weak detections")
args = vars(ap.parse_args())

# initialize our centroid tracker and frame dimensions
ct = CentroidTracker()
(H, W) = (None, None)
 
# load our serialized model from disk
print("[INFO] loading model...")
net = cv2.dnn.readNetFromCaffe(args["prototxt"], args["model"])
 
# initialize the video stream and allow the camera sensor to warmup
print("[INFO] starting video stream...")
vs = VideoStream(src=0).start()
time.sleep(2.0)

# loop over the frames from the video stream
while True:
    # read the next frame from the video stream and resize it
    frame = vs.read()
    frame = imutils.resize(frame, width=400)
 
    # if the frame dimensions are None, grab them
    if W is None or H is None:
        (H, W) = frame.shape[:2]
 
    # construct a blob from the frame, pass it through the network,
    # obtain our output predictions, and initialize the list of
    # bounding box rectangles
    blob = cv2.dnn.blobFromImage(frame, 1.0, (W, H),
        (104.0, 177.0, 123.0))
    net.setInput(blob)
    detections = net.forward()
    rects = []

    # loop over the detections
    for i in range(0, detections.shape[2]):
        # filter out weak detections by ensuring the predicted
        # probability is greater than a minimum threshold
        if detections[0, 0, i, 2] > args["confidence"]:
            # compute the (x, y)-coordinates of the bounding box for
            # the object, then update the bounding box rectangles list
            box = detections[0, 0, i, 3:7] * np.array([W, H, W, H])
            rects.append(box.astype("int"))

            # draw a bounding box surrounding the object so we can
            # visualize it
            (startX, startY, endX, endY) = box.astype("int")
            cv2.rectangle(frame, (startX, startY), (endX, endY),
                (0, 255, 0), 2)
            
    # update our centroid tracker using the computed set of bounding
    # box rectangles
    objects = ct.update(rects)
 
    # loop over the tracked objects
    for (objectID, centroid) in objects.items():
        # draw both the ID of the object and the centroid of the
        # object on the output frame
        text = "ID {}".format(objectID)
        cv2.putText(frame, text, (centroid[0] - 10, centroid[1] - 10),
            cv2.FONT_HERSHEY_SIMPLEX, 0.5, (0, 255, 0), 2)
        cv2.circle(frame, (centroid[0], centroid[1]), 4, (0, 255, 0), -1)
 
    # show the output frame
    cv2.imshow("Frame", frame)
    key = cv2.waitKey(1) & 0xFF
 
    # if the `q` key was pressed, break from the loop
    if key == ord("q"):
        break
 
# do a bit of cleanup
cv2.destroyAllWindows()
vs.stop()

usage: ipykernel_launcher.py [-h] -p PROTOTXT -m MODEL [-c CONFIDENCE]
ipykernel_launcher.py: error: the following arguments are required: -p/--prototxt, -m/--model


SystemExit: 2

/home/zamarseny/anaconda3/envs/nlp/lib/python3.6/site-packages/IPython/core/interactiveshell.py:3299: UserWarning: To exit: use 'exit', 'quit', or Ctrl-D.
  warn("To exit: use 'exit', 'quit', or Ctrl-D.", stacklevel=1)


## rewritten (TF)

In [5]:
# import the necessary packages
#rom pyimagesearch.centroidtracker import CentroidTracker
from imutils.video import VideoStream
import numpy as np
import argparse
import imutils
import time

from time import gmtime, strftime
from datetime import datetime

import cv2

import numpy as np
import os
import six.moves.urllib as urllib
import sys
import tarfile
import tensorflow as tf
import zipfile
 
from collections import defaultdict
from io import StringIO
from matplotlib import pyplot as plt
from PIL import Image
 
from scipy.ndimage import rotate
from scipy.misc import imread, imshow



In [6]:
!cd /home/zamarseny/Data_Science/models/research/object_detection/
!ls

 003-graphcut.ipynb		        caffe_test.ipynb
 003-superpixel.ipynb		        detection_ex.ipynb
 003-tracking_experiments.ipynb         hand
 003-viola-jones.ipynb		        output.avi
 003-watershed.ipynb		       'recognition classes.ipynb'
 another_tracking_from_internet.ipynb   Untitled.ipynb


In [7]:
!ls

anchor_generators
another_tracking.ipynb
box_coders
builders
CONTRIBUTING.md
core
data
data_decoders
dataset_tools
dockerfiles
eval_util.py
eval_util_test.py
exporter.py
exporter_test.py
export_inference_graph.py
export_tflite_ssd_graph_lib.py
export_tflite_ssd_graph_lib_test.py
export_tflite_ssd_graph.py
faster_rcnn_inception_v2_coco_2018_01_28
faster_rcnn_resnet50_coco_2018_01_28
g3doc
inference
__init__.py
inputs.py
inputs_test.py
legacy
local_models.ipynb
mask_rcnn_inception_v2_coco_2018_01_28
matchers
meta_architectures
metrics
model_hparams.py
model_lib.py
model_lib_test.py
model_main.py
models
model_tpu_main.py
object_detection_tutorial.ipynb
other_models
output.avi
pic_from_vid.jpg
predictors
protos
__pycache__
README.md
samples
ssd_mobilenet_v1_coco_11_06_2017
ssd_mobilenet_v1_coco_11_06_2017.tar.gz
ssd_mobilenet_v1_coco_2017_11_17
ssd_mobilenet_v1_coco_2017_11_17.tar.gz
ssd_mobilenet_v2_coco_2018_03_29
test_ckpt
test_data
test_images
Traffic-Light-Detection.ipynb
trax.ipynb
U

In [6]:
#!cd /home/zamarseny/Data_Science/models/research/object_detection/
sys.path.append("..")
#sys.path.append('/home/zamarseny/Data_Science/models/research/object_detection')

#sys.path.insert(0, '/home/zamarseny/Data_Science/models/research/object_detection/utils')

#import file

from utils import label_map_util
 
from utils import visualization_utils as vis_util

#import psutil 

In [7]:
# What model to download.
MODEL_NAME = 'ssd_mobilenet_v2_coco_2018_03_29'
#MODEL_NAME = 'mask_rcnn_inception_v2_coco_2018_01_28'

MODEL_FILE = MODEL_NAME + '.tar.gz'
#DOWNLOAD_BASE = 'http://download.tensorflow.org/models/object_detection/'
DOWNLOAD_BASE = '/home/zamarseny/Data_Science/models/research/object_detection/other_models/'

# Path to frozen detection graph. This is the actual model that is used for the object detection.
PATH_TO_FROZEN_GRAPH = MODEL_NAME + '/frozen_inference_graph.pb'

# List of the strings that is used to add correct label for each box.
PATH_TO_LABELS = os.path.join('data', 'mscoco_label_map.pbtxt')

#opener = urllib.request.URLopener()
#opener.retrieve(DOWNLOAD_BASE + MODEL_FILE, MODEL_FILE)
#tar_file = tarfile.open(MODEL_FILE)
tar_file = tarfile.open(DOWNLOAD_BASE + MODEL_FILE)
for file in tar_file.getmembers():
  file_name = os.path.basename(file.name)
  if 'frozen_inference_graph.pb' in file_name:
    tar_file.extract(file, os.getcwd())
    

detection_graph = tf.Graph()
with detection_graph.as_default():
  od_graph_def = tf.GraphDef()
  with tf.gfile.GFile(PATH_TO_FROZEN_GRAPH, 'rb') as fid:
    serialized_graph = fid.read()
    od_graph_def.ParseFromString(serialized_graph)
    tf.import_graph_def(od_graph_def, name='')


category_index = label_map_util.create_category_index_from_labelmap(PATH_TO_LABELS, use_display_name=True)



In [8]:
def filter_boxes(min_score, boxes, scores, classes, categories):
    """Return boxes with a confidence >= `min_score`"""

    n = len(classes[0])
    #print(n)
    idxs = []
    filtered_boxes=[]
    filtered_scores=[]
    filtered_classes=[]
    for i in range(n):
        if classes[0][i] in categories and scores[0][i] >= min_score:
            idxs.append(i)
            filtered_boxes.append(boxes[0][i])
            filtered_scores.append(scores[0][i])
            filtered_classes.append(classes[0][i])
    
    return np.array([filtered_boxes]), np.array([filtered_scores]), np.array([filtered_classes])

In [12]:
'''
# construct the argument parse and parse the arguments
ap = argparse.ArgumentParser()
ap.add_argument("-p", "--prototxt", required=True,
    help="path to Caffe 'deploy' prototxt file")
ap.add_argument("-m", "--model", required=True,
    help="path to Caffe pre-trained model")
ap.add_argument("-c", "--confidence", type=float, default=0.5,
    help="minimum probability to filter weak detections")
args = vars(ap.parse_args())


# load our serialized model from disk
print("[INFO] loading model...")
net = cv2.dnn.readNetFromCaffe(args["prototxt"], args["model"])
'''
fourcc = cv2.VideoWriter_fourcc(*'MJPG') 

frm_nmb=0

res_hei=480#360#720 #360 #288#576 
res_wid=640

out = cv2.VideoWriter('output.avi', fourcc, 20.0, (res_wid, res_hei)) 

confidence_cutoff = 0.4
interesting_classes =[1]
start_time=datetime.now()


# initialize our centroid tracker and frame dimensions
ct = CentroidTracker()
(H, W) = (None, None)
 
'''    
# initialize the video stream and allow the camera sensor to warmup
print("[INFO] starting video stream...")
vs = VideoStream(src=0).start()
time.sleep(2.0)
'''

#Substitute for Video Stream
#cap = cv2.VideoCapture('rtsp://admin:68gh8h948fh@109.188.95.8:2983/cam/realmonitor?channel=6&subtype=1')
cap = cv2.VideoCapture('/home/zamarseny/Data_Science/input_data/MOT_Challenge_Visualize.mp4')
cap = cv2.VideoCapture('horizontal_panorama.avi'
#cap = cv2.VideoCapture(0)


# loop over the frames from the video stream
#while True: #cap.isOpened(): #True
    # read the next frame from the video stream and resize it
    #frame = vs.read()

with detection_graph.as_default():
  #with tf.Session(graph=detection_graph) as sess:
  with tf.Session(graph=detection_graph\
                  #, config=tf.ConfigProto(gpu_options=gpu_options)\
                 ) as sess:
    while  (cap.isOpened()):
    
        #Substitute for Video Stream
        ret, frame = cap.read()

        #frame = imutils.resize(frame, width=400)
        frame=cv2.resize(frame, (res_wid, res_hei))
 
        # if the frame dimensions are None, grab them
        if W is None or H is None:
            (H, W) = frame.shape[:2]
 
        vis=frame
    
        image_np_expanded = np.expand_dims(vis, axis=0)
        image_tensor = detection_graph.get_tensor_by_name('image_tensor:0')
        # Each box represents a part of the image where a particular object was detected.
        boxes = detection_graph.get_tensor_by_name('detection_boxes:0')
        # Each score represent how level of confidence for each of the objects.
        # Score is shown on the result image, together with the class label.
        
        cur_time=datetime.now()#.strftime('%Y-%m-%d %H:%M:%S')
        d=cur_time-start_time
        #d.seconds
        
        scores = detection_graph.get_tensor_by_name('detection_scores:0')
        classes = detection_graph.get_tensor_by_name('detection_classes:0')
        num_detections = detection_graph.get_tensor_by_name('num_detections:0')
        # Actual detection.
        (boxes, scores, classes, num_detections) = sess.run(
          [boxes, scores, classes, num_detections],
          feed_dict={image_tensor: image_np_expanded})
        
        # Visualization of the results of a detection.
        # Filter boxes with a confidence score less than `confidence_cutoff`
        boxes, scores, classes = filter_boxes(confidence_cutoff, boxes, scores, classes, interesting_classes)
        
        vis_util.visualize_boxes_and_labels_on_image_array(
            vis,
            np.squeeze(boxes),
            np.squeeze(classes).astype(np.int32),
            np.squeeze(scores),
            category_index,
            use_normalized_coordinates=True,
            line_thickness=2)

        '''
        # construct a blob from the frame, pass it through the network,
        # obtain our output predictions, and initialize the list of
        # bounding box rectangles
        blob = cv2.dnn.blobFromImage(frame, 1.0, (W, H),
            (104.0, 177.0, 123.0))
        net.setInput(blob)
        detections = net.forward()
        rects = []
    
        '''

    
        '''
        # loop over the detections
        for i in range(0, detections.shape[2]):
            # filter out weak detections by ensuring the predicted
            # probability is greater than a minimum threshold
            if detections[0, 0, i, 2] > conf #args["confidence"]:
                # compute the (x, y)-coordinates of the bounding box for
                # the object, then update the bounding box rectangles list
                box = detections[0, 0, i, 3:7] * np.array([W, H, W, H])
                rects.append(box.astype("int"))

                # draw a bounding box surrounding the object so we can
                # visualize it
                (startX, startY, endX, endY) = box.astype("int")
                cv2.rectangle(frame, (startX, startY), (endX, endY),
                    (0, 255, 0), 2)
        '''    
        # update our centroid tracker using the computed set of bounding
        # box rectangles
        multipl=np.array([[res_wid, 0, 0, 0], [0, res_hei, 0, 0 ], [0, 0, res_wid, 0], [0, 0, 0, res_hei]])
        rects=np.array(np.matmul(boxes[0], multipl), int)

        objects = ct.update(rects) #rects
 
        # loop over the tracked objects
        for (objectID, centroid) in objects.items():
            # draw both the ID of the object and the centroid of the
            # object on the output frame
            text = "ID {}".format(objectID)
            cv2.putText(vis, text, (centroid[0] - 10, centroid[1] - 10),
            cv2.FONT_HERSHEY_SIMPLEX, 0.5, (0, 0, 255), 2)
            cv2.circle(vis, (centroid[0], centroid[1]), 6, (0, 0, 255), -1)
        ''' 
        '''
        # show the output frame
        cv2.imshow("Frame", vis)
        out.write(vis)
        key = cv2.waitKey(1) & 0xFF
 
        # if the `q` key was pressed, break from the loop
        if key == ord("q"):
            break
 
# do a bit of cleanup
cap.release()
cv2.destroyAllWindows()
#vs.stop()

In [31]:
vis.shape[:2]

(left, right, top, bottom) = (xmin * im_width, xmax * im_width, 
                              ymin * im_height, ymax * im_height)

(480, 640)

In [1]:
print(boxes.shape)
print(boxes[0])
multipl=np.array([[100, 0, 0, 0], [0, 200, 0, 0 ], [0, 0, 100, 0], [0, 0, 0, 200]])
print(multipl)
rect=np.array(np.matmul(boxes[0], multipl), int)
rect

NameError: name 'boxes' is not defined

In [2]:
ymin = (boxes[0,:,0]*res_hei)
xmin = (boxes[0,:,1]*res_wid)
ymax = (boxes[0,:,2]*res_hei)
xmax = (boxes[0,:,3]*res_wid)

#print(ymin)

print(np.array(xmin, int))
rect=np.concatenate(np.array(ymin, int), np.array(xmin, int))
rect=np.concatenate(rect, np.array(ymin, int))
rect=rect=np.concatenate(rect, np.array(ymin, int))

NameError: name 'boxes' is not defined

In [23]:
objects

OrderedDict([(1, array([186, 217])),
             (2, array([163, 211])),
             (4, array([308, 236])),
             (5, array([180, 233])),
             (7, array([200, 143])),
             (8, array([150, 341])),
             (9, array([128, 287])),
             (10, array([226, 117]))])

In [26]:
scores

array([[0.5540281]], dtype=float32)

In [9]:
i

NameError: name 'i' is not defined